# Generated by Django 5.0.4 on 2024-04-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                default="item_images/default.jpg", upload_to="item_images/"
            ),
            preserve_default=False,
        ),
    ]
