# Generated by Django 5.0.4 on 2024-04-08 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_item_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_items", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
